#!/bin/sh

##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_USER="$(id -un 2>/dev/null || true)"

OPENBATON_FANCY_PROJECT_NAME="Open Baton Dummy VNFM AMQP"         # Used for logging and other printings
OPENBATON_PROJECT_NAME="openbaton-vnfm-dummy-amqp"                # Used for process checkings (it should be equal to the debian package's name)
OPENBATON_BASE_DIR=/usr
OPENBATON_EXE_FOLDER=$OPENBATON_BASE_DIR/bin

OPENBATON_AUTOSTART_DEFAULT=true
OPENBATON_AUTOSTART=${OPENBATON_AUTOSTART:-$OPENBATON_AUTOSTART_DEFAULT}


##############################
#### Execution privileges ####
##############################

checkBinary () {
    if command -v $1 >/dev/null 2>&1 ; then
        log_success_msg "Checking for '$1'"
        return 0
    else
        log_failure_msg "Checking for '$1'"
        return 1
    fi
}

_ex='sh -c'
if [ "${OPENBATON_USER}" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


##########################################
#### Configure  ####
##########################################

#createLogsFolder () {
#    if [ ! -d "${_PROJECT_LOGS_FOLDER}" ]; then
#        $_ex 'mkdir -p '"$_PROJECT_LOGS_FOLDER"
#        log_success_msg "Created log folder \"${_PROJECT_LOGS_FOLDER}\""
#    fi
#    $_ex 'chown -R '"$_USER $_PROJECT_LOGS_FOLDER"
#    log_success_msg "Configured permissions of log folder \"${_PROJECT_LOGS_FOLDER}\""
#}

configure() {
    log_success_msg "Configuring $OPENBATON_FANCY_PROJECT_NAME installation .."
    $_ex "chmod a+x ${OPENBATON_EXE_FOLDER}/$OPENBATON_PROJECT_NAME"
    log_success_msg "$OPENBATON_FANCY_PROJECT_NAME installation completed"

    # Allow the use of the .deb package to install Open Baton with Docker (the Docker file developer need to manage the starting of the $_FANCY_PROJECT_NAME in the Docker file)
    if [ "${OPENBATON_AUTOSTART}" = "true" ]; then
        if $_ex 'systemctl start openbaton-vnfm-dummy-amqp.service' >/dev/null 2>&1 ; then
            log_success_msg "Starting the $OPENBATON_FANCY_PROJECT_NAME .."
            continue
        elif $_ex 'start openbaton-vnfm-dummy-amqp' >/dev/null 2>&1 ; then
            log_success_msg "Starting the $OPENBATON_FANCY_PROJECT_NAME .."
            continue
        else
            log_failure_msg "Starting the $OPENBATON_FANCY_PROJECT_NAME"
        fi
    fi
}
                                                                                   
configure
